[externals] remove _NUMERICS_INTERNAL_CXX_, breaks lapack linkage when BUILD_AS_CPP
fixes e.g.,

    ../../../libsiconos_numerics.so.5.0.0: undefined reference to `clapack_dgetrf(CBLAS_ORDER, int, int, double*, int, int*)'

when BUILD_AS_CPP=YES and linking Atlas.